//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBX.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLBXEntities : DbContext
    {
        public QLBXEntities()
            : base("name=QLBXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BENXE> BENXEs { get; set; }
        public virtual DbSet<CHITIETVE> CHITIETVEs { get; set; }
        public virtual DbSet<GIOKHOIHANH> GIOKHOIHANHs { get; set; }
        public virtual DbSet<GUIHANGHOA> GUIHANGHOAs { get; set; }
        public virtual DbSet<KHACHDIXE> KHACHDIXEs { get; set; }
        public virtual DbSet<LOAIBANGLAI> LOAIBANGLAIs { get; set; }
        public virtual DbSet<LOAIXE> LOAIXEs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<NHANVIENXE> NHANVIENXEs { get; set; }
        public virtual DbSet<PERMISSION> PERMISSIONs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
        public virtual DbSet<VEXE> VEXEs { get; set; }
        public virtual DbSet<XE> XEs { get; set; }
        public virtual DbSet<TUYENXE> TUYENXEs { get; set; }
        public virtual DbSet<CHUYENXE> CHUYENXEs { get; set; }
    }
}
