//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBX.Model
{
    using QLBX.ViewModel;
    using System;
    using System.Collections.Generic;

    public partial class NHANVIENXE : BaseViewModel
    {
        private int _iDNHANVIENXE;
        private string _hOTEN;
        private string _cMND;
        private DateTime? _nAMSINH;
        private string _dIACHI;
        private string _sDT;
        private int? _bANGLAI;
        private DateTime? _nGAYTHAMGIA;
        private int? _lOAINHANVIEN;
        private int? _bENHIENTAI;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIENXE()
        {
            this.CHUYENXEs = new HashSet<CHUYENXE>();
            this.CHUYENXEs1 = new HashSet<CHUYENXE>();
            this.CHUYENXEs2 = new HashSet<CHUYENXE>();
            this.CHUYENXEs3 = new HashSet<CHUYENXE>();
        }

        public int IDNHANVIENXE { get => _iDNHANVIENXE; set { _iDNHANVIENXE = value; OnPropertyChanged(); } }
        public string HOTEN { get => _hOTEN; set { _hOTEN = value; OnPropertyChanged(); } }
        public string CMND { get => _cMND; set { _cMND = value; OnPropertyChanged(); } }
        public Nullable<System.DateTime> NAMSINH { get => _nAMSINH; set { _nAMSINH = value; OnPropertyChanged(); } }
        public string DIACHI { get => _dIACHI; set { _dIACHI = value; OnPropertyChanged(); } }
        public string SDT { get => _sDT; set { _sDT = value; OnPropertyChanged(); } }
        public Nullable<int> BANGLAI { get => _bANGLAI; set { _bANGLAI = value; OnPropertyChanged(); } }
        public Nullable<System.DateTime> NGAYTHAMGIA { get => _nGAYTHAMGIA; set { _nGAYTHAMGIA = value; OnPropertyChanged(); } }
        public Nullable<int> LOAINHANVIEN { get => _lOAINHANVIEN; set { _lOAINHANVIEN = value; OnPropertyChanged(); } }
        public Nullable<int> BENHIENTAI { get => _bENHIENTAI; set { _bENHIENTAI = value; OnPropertyChanged(); } }

        public virtual LOAIBANGLAI LOAIBANGLAI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUYENXE> CHUYENXEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUYENXE> CHUYENXEs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUYENXE> CHUYENXEs2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUYENXE> CHUYENXEs3 { get; set; }
    }
}
