//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBX.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISSION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERMISSION()
        {
            this.USERs = new HashSet<USER>();
        }
    
        public string IDPermission { get; set; }
        public string NamePermission { get; set; }
        public Nullable<bool> ve { get; set; }
        public Nullable<bool> chuyen { get; set; }
        public Nullable<bool> tuyen { get; set; }
        public Nullable<bool> thongke { get; set; }
        public Nullable<bool> nhanvien { get; set; }
        public Nullable<bool> khachdixe { get; set; }
        public Nullable<bool> khachguihang { get; set; }
        public Nullable<bool> hanghoa { get; set; }
        public Nullable<bool> nhanvienxe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER> USERs { get; set; }
    }
}
