//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBX.Model
{
    using QLBX.ViewModel;
    using System;
    using System.Collections.Generic;

    public partial class TUYENXE : BaseViewModel
    {
        private int _iDTUYEN;
        private int? _bENDI;
        private int? _bENDEN;
        private decimal? _gIAVEMATDINH;
        private DateTime? _nGAYCAPNHATGIA;
        private int? _qUANDUONG;
        private TimeSpan? _tHOIGIANDI;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUYENXE()
        {
            this.CHUYENXEs = new HashSet<CHUYENXE>();
        }

        public int IDTUYEN { get => _iDTUYEN; set { _iDTUYEN = value; OnPropertyChanged(); } }
        public Nullable<int> BENDI
        {
            get => _bENDI; set { _bENDI = value; OnPropertyChanged(); }
        }
        public Nullable<int> BENDEN { get => _bENDEN; set { _bENDEN = value; OnPropertyChanged(); } }
        public Nullable<decimal> GIAVEMATDINH { get => _gIAVEMATDINH; set { _gIAVEMATDINH = value; OnPropertyChanged(); } }
        public Nullable<System.DateTime> NGAYCAPNHATGIA { get => _nGAYCAPNHATGIA; set { _nGAYCAPNHATGIA = value; OnPropertyChanged(); } }
        public Nullable<int> QUANDUONG { get => _qUANDUONG; set { _qUANDUONG = value; OnPropertyChanged(); } }
        public Nullable<System.TimeSpan> THOIGIANDI { get => _tHOIGIANDI; set { _tHOIGIANDI = value; OnPropertyChanged(); } }

        public virtual BENXE BENXE { get; set; }
        public virtual BENXE BENXE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUYENXE> CHUYENXEs { get; set; }
    }
}
