//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBX.Model
{
    using QLBX.ViewModel;
    using System;
    using System.Collections.Generic;

    public partial class XE : BaseViewModel
    {
        private string _bIENSO;
        private string _nHASANXUAT;
        private DateTime? _nGAYMUA;
        private int? _iDLOAI;
        private int? _bENHIENTAI;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XE()
        {
            this.CHUYENXEs = new HashSet<CHUYENXE>();
        }

        public string BIENSO { get => _bIENSO; set { _bIENSO = value; OnPropertyChanged(); } }
        public string NHASANXUAT { get => _nHASANXUAT; set { _nHASANXUAT = value; OnPropertyChanged(); } }
        public Nullable<System.DateTime> NGAYMUA { get => _nGAYMUA; set { _nGAYMUA = value; OnPropertyChanged(); } }
        public Nullable<int> IDLOAI { get => _iDLOAI; set { _iDLOAI = value; OnPropertyChanged(); } }
        public Nullable<int> BENHIENTAI { get => _bENHIENTAI; set { _bENHIENTAI = value; OnPropertyChanged(); } }

        public virtual LOAIXE LOAIXE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUYENXE> CHUYENXEs { get; set; }
    }
}
